<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [ 'name' => [ 'ru' => 'Ирак', 'en' =>  'Iraq' ] ],
            [ 'name' => [ 'ru' => 'Грузия', 'en' =>  'Georgia' ] ],
            [ 'name' => [ 'ru' => 'Мексика', 'en' =>  'Mexico' ] ],
            [ 'name' => [ 'ru' => 'Белиз', 'en' =>  'Belize' ] ],
            [ 'name' => [ 'ru' => 'Аруба', 'en' =>  'Aruba' ] ],
            [ 'name' => [ 'ru' => 'Бутан', 'en' =>  'Bhutan' ] ],
            [ 'name' => [ 'ru' => 'Дания', 'en' =>  'Denmark' ] ],
            [ 'name' => [ 'ru' => 'Монголия', 'en' =>  'Mongolia' ] ],
            [ 'name' => [ 'ru' => 'Монако', 'en' =>  'Monaco' ] ],
            [ 'name' => [ 'ru' => 'Гаити', 'en' =>  'Haiti' ] ],
            [ 'name' => [ 'ru' => 'Ирландия', 'en' =>  'Ireland' ] ],
            [ 'name' => [ 'ru' => 'Мали', 'en' =>  'Mali' ] ],
            [ 'name' => [ 'ru' => 'Конго', 'en' =>  'Congo' ] ],
            [ 'name' => [ 'ru' => 'Гуам', 'en' =>  'Guam' ] ],
            [ 'name' => [ 'ru' => 'Ангола', 'en' =>  'Angola' ] ],
            [ 'name' => [ 'ru' => 'Куба', 'en' =>  'Cuba' ] ],
            [ 'name' => [ 'ru' => 'Лаос', 'en' =>  'Laos' ] ],
            [ 'name' => [ 'ru' => 'Ливия', 'en' =>  'Libya' ] ],
            [ 'name' => [ 'ru' => 'Гана', 'en' =>  'Ghana' ] ],
            [ 'name' => [ 'ru' => 'Гамбия', 'en' =>  'Gambia' ] ],
            [ 'name' => [ 'ru' => 'Бельгия', 'en' =>  'Belgium' ] ],
            [ 'name' => [ 'ru' => 'Бенин', 'en' =>  'Benin' ] ],
            [ 'name' => [ 'ru' => 'Джибути', 'en' =>  'Djibouti' ] ],
            [ 'name' => [ 'ru' => 'Кипр', 'en' =>  'Cyprus' ] ],
            [ 'name' => [ 'ru' => 'Молдова', 'en' =>  'Moldova' ] ],
            [ 'name' => [ 'ru' => 'Латвия', 'en' =>  'Latvia' ] ],
            [ 'name' => [ 'ru' => 'Италия', 'en' =>  'Italy' ] ],
            [ 'name' => [ 'ru' => 'Китай', 'en' =>  'China' ] ],
            [ 'name' => [ 'ru' => 'Замбия', 'en' =>  'Zambia' ] ],
            [ 'name' => [ 'ru' => 'Гвинея', 'en' =>  'Guinea' ] ],
            [ 'name' => [ 'ru' => 'Макао', 'en' =>  'Macau' ] ],
            [ 'name' => [ 'ru' => 'Индия', 'en' =>  'India' ] ],
            [ 'name' => [ 'ru' => 'Кения', 'en' =>  'Kenya' ] ],
            [ 'name' => [ 'ru' => 'Малави', 'en' =>  'Malawi' ] ],
            [ 'name' => [ 'ru' => 'Гайана', 'en' =>  'Guiana' ] ],
            [ 'name' => [ 'ru' => 'Йемен', 'en' =>  'Yemen' ] ],
            [ 'name' => [ 'ru' => 'Катар', 'en' =>  'Qatar' ] ],
            [ 'name' => [ 'ru' => 'Малайзия', 'en' =>  'Malaysia' ] ],
            [ 'name' => [ 'ru' => 'Коморы', 'en' =>  'Comoros' ] ],
            [ 'name' => [ 'ru' => 'Маврикий', 'en' =>  'Maurícia' ] ],
            [ 'name' => [ 'ru' => 'Мьянма', 'en' =>  'Myanmar' ] ],
            [ 'name' => [ 'ru' => 'Германия', 'en' =>  'Germany' ] ],
            [ 'name' => [ 'ru' => 'Науру', 'en' =>  'Nauru' ] ],
            [ 'name' => [ 'ru' => 'Непал', 'en' =>  'Nepal' ] ],
            [ 'name' => [ 'ru' => 'Ватикан', 'en' =>  'Vatican' ] ],
            [ 'name' => [ 'ru' => 'Уганда', 'en' =>  'Uganda' ] ],
            [ 'name' => [ 'ru' => 'Эстония', 'en' =>  'Estonia' ] ],
            [ 'name' => [ 'ru' => 'Сингапур', 'en' =>  'Singapore' ] ],
            [ 'name' => [ 'ru' => 'Ямайка', 'en' =>  'Jamaica' ] ],
            [ 'name' => [ 'ru' => 'Нигер', 'en' =>  'Niger' ] ],
            [ 'name' => [ 'ru' => 'Россия', 'en' =>  'Russia' ] ],
            [ 'name' => [ 'ru' => 'Никарагуа', 'en' =>  'Nicaragua' ] ],
            [ 'name' => [ 'ru' => 'Эфиопия', 'en' =>  'Ethiopia' ] ],
            [ 'name' => [ 'ru' => 'Сербия', 'en' =>  'Serbia' ] ],
            [ 'name' => [ 'ru' => 'Габон', 'en' =>  'Gabon' ] ],
            [ 'name' => [ 'ru' => 'Турция', 'en' =>  'Turkey' ] ],
            [ 'name' => [ 'ru' => 'Судан', 'en' =>  'Sudan' ] ],
            [ 'name' => [ 'ru' => 'Багамы', 'en' =>  'Bahamas' ] ],
            [ 'name' => [ 'ru' => 'Ниуэ', 'en' =>  'Niue' ] ],
            [ 'name' => [ 'ru' => 'Того', 'en' =>  'Togo' ] ],
            [ 'name' => [ 'ru' => 'Хорватия', 'en' =>  'Croatia' ] ],
            [ 'name' => [ 'ru' => 'Бахрейн', 'en' =>  'Bahrain' ] ],
            [ 'name' => [ 'ru' => 'Таиланд', 'en' =>  'Thailand' ] ],
            [ 'name' => [ 'ru' => 'Сомали', 'en' =>  'Somalia' ] ],
            [ 'name' => [ 'ru' => 'Палау', 'en' =>  'Palau' ] ],
            [ 'name' => [ 'ru' => 'Токелау', 'en' =>  'Tokelau' ] ],
            [ 'name' => [ 'ru' => 'Франция', 'en' =>  'France' ] ],
            [ 'name' => [ 'ru' => 'Финляндия', 'en' =>  'Finland' ] ],
            [ 'name' => [ 'ru' => 'Израиль', 'en' =>  'Israel' ] ], 
            [ 'name' => [ 'ru' => 'Шри-Ланка', 'en' =>  'Sri Lanka' ] ], 
            [ 'name' => [ 'ru' => 'Самоа', 'en' =>  'Samoa' ] ], 
            [ 'name' => [ 'ru' => 'Сенегал', 'en' =>  'Senegal' ] ],
            [ 'name' => [ 'ru' => 'Свазиленд', 'en' =>  'Swaziland' ] ],
            [ 'name' => [ 'ru' => 'Бермуды', 'en' =>  'Bermuda' ] ],
            [ 'name' => [ 'ru' => 'Словения', 'en' =>  'Slovenia' ] ],
            [ 'name' => [ 'ru' => 'Тайвань', 'en' =>  'Taiwan' ] ],
            [ 'name' => [ 'ru' => 'Чили', 'en' =>  'Chile' ] ],
            [ 'name' => [ 'ru' => 'США', 'en' =>  'USA' ] ],
            [ 'name' => [ 'ru' => 'Фиджи', 'en' =>  'Fiji' ] ],
            [ 'name' => [ 'ru' => 'Тувалу', 'en' =>  'Tuvalu' ] ],
            [ 'name' => [ 'ru' => 'Норвегия', 'en' =>  'Norway' ] ],
            [ 'name' => [ 'ru' => 'Руанда', 'en' =>  'Rwanda' ] ],
            [ 'name' => [ 'ru' => 'Чад', 'en' =>  'Chad' ] ],
            [ 'name' => [ 'ru' => 'Остров Мэн', 'en' =>  'Isle of Man' ] ], 
            [ 'name' => [ 'ru' => 'Оман', 'en' =>  'Oman' ] ],
            [ 'name' => [ 'ru' => 'Панама', 'en' =>  'Panama' ] ],
            [ 'name' => [ 'ru' => 'Перу', 'en' =>  'Peru' ] ],
            [ 'name' => [ 'ru' => 'Реюньон', 'en' =>  'Reunion' ] ],
            [ 'name' => [ 'ru' => 'Эквадор', 'en' =>  'Ecuador' ] ],
            [ 'name' => [ 'ru' => 'Кыргызстан', 'en' =>  'Kyrgyzstan' ] ],
            [ 'name' => [ 'ru' => 'Иран', 'en' =>  'Iran' ] ],
            [ 'name' => [ 'ru' => 'Сейшелы', 'en' =>  'Seychelles' ] ],
            [ 'name' => [ 'ru' => 'Марокко', 'en' =>  'Morocco' ] ],
            [ 'name' => [ 'ru' => 'КабоВерде', 'en' =>  'Cape Verde' ] ], 
            [ 'name' => [ 'ru' => 'Доминика', 'en' =>  'Dominica' ] ],
            [ 'name' => [ 'ru' => 'Острова Кайман', 'en' =>  'Cayman Islands' ] ], 
            [ 'name' => [ 'ru' => 'Зимбабве', 'en' =>  'Zimbabwe' ] ],
            [ 'name' => [ 'ru' => 'Саудовская Аравия', 'en' =>  'Saudi Arabia' ] ], 
            [ 'name' => [ 'ru' => 'Гренада', 'en' =>  'Grenada' ] ],
            [ 'name' => [ 'ru' => 'Монтсеррат', 'en' =>  'Montserrat' ] ],
            [ 'name' => [ 'ru' => 'Мальта', 'en' =>  'Malta' ] ],
            [ 'name' => [ 'ru' => 'Таджикистан', 'en' =>  'Tajikistan' ] ],
            [ 'name' => [ 'ru' => 'Уругвай', 'en' =>  'Uruguay' ] ],
            [ 'name' => [ 'ru' => 'Казахстан', 'en' =>  'Kazakhstan' ] ],
            [ 'name' => [ 'ru' => 'Тунис', 'en' =>  'Tunisia' ] ],
            [ 'name' => [ 'ru' => 'Канада', 'en' =>  'Canada' ] ],
            [ 'name' => [ 'ru' => 'Восточный Тимор', 'en' =>  'East Timor' ] ], 
            [ 'name' => [ 'ru' => 'Ангилья', 'en' =>  'Anguilla' ] ],
            [ 'name' => [ 'ru' => 'Тонга', 'en' =>  'Tonga' ] ],
            [ 'name' => [ 'ru' => 'Индонезия', 'en' =>  'Indonesia' ] ],
            [ 'name' => [ 'ru' => 'Синт-Мартен', 'en' =>  'Sint Maarten' ] ], 
            [ 'name' => [ 'ru' => 'Мозамбик', 'en' =>  'Mozambique' ] ],
            [ 'name' => [ 'ru' => 'Болгария', 'en' =>  'Bulgaria' ] ],
            [ 'name' => [ 'ru' => 'Иордания', 'en' =>  'Jordan' ] ],
            [ 'name' => [ 'ru' => 'Греция', 'en' =>  'Greece' ] ],
            [ 'name' => [ 'ru' => 'Либерия', 'en' =>  'Liberia' ] ],
            [ 'name' => [ 'ru' => 'Словакия', 'en' =>  'Slovakia' ] ],
            [ 'name' => [ 'ru' => 'Коста-Рика', 'en' =>  'Costa Rica' ] ], 
            [ 'name' => [ 'ru' => 'Румыния', 'en' =>  'Romania' ] ],
            [ 'name' => [ 'ru' => 'Намибия', 'en' =>  'Namibia' ] ],
            [ 'name' => [ 'ru' => 'Лесото', 'en' =>  'Lesotho' ] ],
            [ 'name' => [ 'ru' => 'Македония', 'en' =>  'Macedonia' ] ],
            [ 'name' => [ 'ru' => 'Гонконг', 'en' =>  'Hong Kong' ] ], 
            [ 'name' => [ 'ru' => 'Ливан', 'en' =>  'Lebanon' ] ],
            [ 'name' => [ 'ru' => 'Нигерия', 'en' =>  'Nigeria' ] ],
            [ 'name' => [ 'ru' => 'Танзания', 'en' =>  'Tanzania' ] ],
            [ 'name' => [ 'ru' => 'Тринидад и Тобаго', 'en' =>  'Trinidad and Tobago' ] ], 
            [ 'name' => [ 'ru' => 'Гватемала', 'en' =>  'Guatemala' ] ],
            [ 'name' => [ 'ru' => 'Пакистан', 'en' =>  'Pakistan' ] ],
            [ 'name' => [ 'ru' => 'Япония', 'en' =>  'Japan' ] ],
            [ 'name' => [ 'ru' => 'Азербайджан', 'en' =>  'Azerbaijan' ] ],
            [ 'name' => [ 'ru' => 'Гибралтар', 'en' =>  'Gibraltar' ] ],
            [ 'name' => [ 'ru' => 'Западная Сахара', 'en' =>  'Western Sahara' ] ], 
            [ 'name' => [ 'ru' => 'Мартиника', 'en' =>  'Martinique' ] ],
            [ 'name' => [ 'ru' => 'Узбекистан', 'en' =>  'Uzbekistan' ] ],
            [ 'name' => [ 'ru' => 'Венгрия', 'en' =>  'Hungary' ] ],
            [ 'name' => [ 'ru' => 'Люксембург', 'en' =>  'Luxembourg' ] ],
            [ 'name' => [ 'ru' => 'Филиппины', 'en' =>  'Philippines' ] ],
            [ 'name' => [ 'ru' => 'Бразилия', 'en' =>  'Brazil' ] ],
            [ 'name' => [ 'ru' => 'Испания', 'en' =>  'Spain' ] ],
            [ 'name' => [ 'ru' => 'Уоллис и Футуна', 'en' =>  'Wallis and Futuna' ] ], 
            [ 'name' => [ 'ru' => 'Австрия', 'en' =>  'Austria' ] ],
            [ 'name' => [ 'ru' => 'Мавритания', 'en' =>  'Mauritania' ] ],
            [ 'name' => [ 'ru' => 'Афганистан', 'en' =>  'Afghanistan' ] ],
            [ 'name' => [ 'ru' => 'Литва', 'en' =>  'Lituania' ] ],
            [ 'name' => [ 'ru' => 'Беларусь', 'en' =>  'Belarus' ] ],
            [ 'name' => [ 'ru' => 'Швейцария', 'en' =>  'Switzerland' ] ],
            [ 'name' => [ 'ru' => 'Новая Каледония', 'en' =>  'New Caledonia' ] ], 
            [ 'name' => [ 'ru' => 'Кюрасао', 'en' =>  'Curacao' ] ],
            [ 'name' => [ 'ru' => 'Фарерские острова', 'en' =>  'Faroe Islands' ] ], 
            [ 'name' => [ 'ru' => 'Туркменистан', 'en' =>  'Turkmenistan' ] ],
            [ 'name' => [ 'ru' => 'Боливия', 'en' =>  'Bolivia' ] ],
            [ 'name' => [ 'ru' => 'Папуа-Новая Гвинея', 'en' =>  'Papua New Guinea' ] ], 
            [ 'name' => [ 'ru' => 'Соломоновы Острова', 'en' =>  'Solomon Islands' ] ], 
            [ 'name' => [ 'ru' => 'Великобритания', 'en' =>  'United Kingdom' ] ], 
            [ 'name' => [ 'ru' => 'Мадагаскар', 'en' =>  'Madagascar Guinea' ] ],
            [ 'name' => [ 'ru' => 'Экваториальная Гвинея', 'en' =>  'Equatorial' ] ], 
            [ 'name' => [ 'ru' => 'Камерун', 'en' =>  'Cameroon' ] ],
            [ 'name' => [ 'ru' => 'Бруней-Даруссалам', 'en' =>  'Brunei Darussalam' ] ], 
            [ 'name' => [ 'ru' => 'Украина', 'en' =>  'Ukraine' ] ],
            [ 'name' => [ 'ru' => 'Черногория', 'en' =>  'Montenegro Leone' ] ],
            [ 'name' => [ 'ru' => 'Сьерра-Леоне', 'en' =>  'Sierra' ] ], 
            [ 'name' => [ 'ru' => 'Сальвадор', 'en' =>  'El Salvador' ] ], 
            [ 'name' => [ 'ru' => 'Новая Зеландия', 'en' =>  'New Zealand' ] ], 
            [ 'name' => [ 'ru' => 'Сирийская Арабская Республика', 'en' =>  'Syria' ] ],
            [ 'name' => [ 'ru' => 'Французская Гвиана', 'en' =>  'French Guiana' ] ], 
            [ 'name' => [ 'ru' => 'Австралия', 'en' =>  'Australia' ] ],
            [ 'name' => [ 'ru' => 'Андорра', 'en' =>  'Andorra' ] ],
            [ 'name' => [ 'ru' => 'Венесуэла', 'en' =>  'Venezuela' ] ],
            [ 'name' => [ 'ru' => 'Объединенные Арабские Эмираты', 'en' =>  'United Arab Emirates' ] ], 
            [ 'name' => [ 'ru' => 'Сан-Марино', 'en' =>  'San Marino' ] ], 
            [ 'name' => [ 'ru' => 'Гвинея-Бисау', 'en' =>  'Guinea -Bissau' ] ],
            [ 'name' => [ 'ru' => 'Бангладеш', 'en' =>  'Bangladesh' ] ],
            [ 'name' => [ 'ru' => 'Ботсвана', 'en' =>  'Botswana' ] ],
            [ 'name' => [ 'ru' => 'Албания', 'en' =>  'Albania' ] ],
            [ 'name' => [ 'ru' => 'Гренландия', 'en' =>  'Greenland' ] ],
            [ 'name' => [ 'ru' => 'Южный Судан', 'en' =>  'South Sudan' ] ], 
            [ 'name' => [ 'ru' => 'Северная Корея', 'en' =>  'North Korea' ] ], 
            [ 'name' => [ 'ru' => 'Остров Норфолк', 'en' =>  'Norfolk Island' ] ], 
            [ 'name' => [ 'ru' => 'Виргинские острова, США', 'en' =>  'US Virgin Islands' ] ], 
            [ 'name' => [ 'ru' => 'Гондурас', 'en' =>  'Honduras' ] ],
            [ 'name' => [ 'ru' => 'Доминиканская Республика', 'en' =>  'Dominican Republic' ] ], 
            [ 'name' => [ 'ru' => 'Гваделупа', 'en' =>  'Guadeloupe' ] ],
            [ 'name' => [ 'ru' => 'Кувейт', 'en' =>  'Kuwait' ] ],
            [ 'name' => [ 'ru' => 'Центрально-Африканская Республика', 'en' =>  'Central African Republic' ] ], 
            [ 'name' => [ 'ru' => 'Северные Марианские острова', 'en' =>  'Northern Mariana Islands' ] ], 
            [ 'name' => [ 'ru' => 'Чехия', 'en' =>  'Czech Republic' ] ], 
            [ 'name' => [ 'ru' => 'Нидерланды', 'en' =>  'Netherlands' ] ],
            [ 'name' => [ 'ru' => 'Виргинские острова, Британские', 'en' =>  'British Virgin Islands' ] ], 
            [ 'name' => [ 'ru' => 'Сан-Томе и Принсипи', 'en' =>  'São Tomé and Príncipe' ] ],
            [ 'name' => [ 'ru' => 'Бурунди', 'en' =>  'Burundi' ] ],
            [ 'name' => [ 'ru' => 'Суринам', 'en' =>  'Suriname' ] ],
            [ 'name' => [ 'ru' => 'Острова Кука', 'en' =>  'Cook Islands' ] ], 
            [ 'name' => [ 'ru' => 'Святая Елена', 'en' =>  'Saint Helena' ] ], 
            [ 'name' => [ 'ru' => 'Сент-Китс и Невис', 'en' =>  'Saint Kitts and Nevis' ] ], 
            [ 'name' => [ 'ru' => 'Фолклендские острова', 'en' =>  'Falkland Islands' ] ], 
            [ 'name' => [ 'ru' => 'Вануату', 'en' =>  'Vanuatu' ] ],
            [ 'name' => [ 'ru' => 'Южная Корея', 'en' =>  'South Korea' ] ], 
            [ 'name' => [ 'ru' => 'Южно-Африканская Республика', 'en' =>  'South Africa' ] ], 
            [ 'name' => [ 'ru' => 'Вьетнам', 'en' =>  'Vietnam' ] ],
            [ 'name' => [ 'ru' => 'Конго демократическая республика', 'en' =>  'Congo Democratic Republic' ] ], 
            [ 'name' => [ 'ru' => 'Египет', 'en' =>  'Egypt' ] ],
            [ 'name' => [ 'ru' => 'Кирибати', 'en' =>  'Kiribati' ] ],
            [ 'name' => [ 'ru' => 'Пуэрто-Рико', 'en' =>  'Puerto Rico' ] ], 
            [ 'name' => [ 'ru' => 'Эритрея', 'en' =>  'Eritrea' ] ],
            [ 'name' => [ 'ru' => 'Французская Полинезия', 'en' =>  'French Polynesia' ] ], 
            [ 'name' => [ 'ru' => 'Острова Теркс и Кайкос', 'en' =>  'Turks and Caicos Islands' ] ], 
            [ 'name' => [ 'ru' => 'Парагвай', 'en' =>  'Paraguay' ] ],
            [ 'name' => [ 'ru' => 'Польша', 'en' =>  'Poland' ] ],
            [ 'name' => [ 'ru' => 'Сент-Винсент', 'en' =>  'Saint Vincent and the Grenadines' ] ], 
            [ 'name' => [ 'ru' => 'Палестинская автономия', 'en' =>  'Palestine' ] ],
            [ 'name' => [ 'ru' => 'Шпицберген и Ян Майен', 'en' =>  'Svalbard and Jan Mayen' ] ], 
            [ 'name' => [ 'ru' => 'Алжир', 'en' =>  'Algeria' ] ],
            [ 'name' => [ 'ru' => 'Барбадос', 'en' =>  'Barbados' ] ],
            [ 'name' => [ 'ru' => 'Буркина-Фасо', 'en' =>  'Burkina Faso' ] ], 
            [ 'name' => [ 'ru' => 'Колумбия', 'en' =>  'Colombia' ] ],
            [ 'name' => [ 'ru' => 'Исландия', 'en' =>  'Iceland' ] ],
            [ 'name' => [ 'ru' => 'Мальдивы', 'en' =>  'Maldives' ] ],
            [ 'name' => [ 'ru' => 'Маршалловы Острова', 'en' =>  'Marshall Islands' ] ], 
            [ 'name' => [ 'ru' => 'Микронезия федеративные штаты', 'en' =>  'Micronesia' ] ],
            [ 'name' => [ 'ru' => 'Питкерн', 'en' =>  'Pitcairn Islands' ] ], 
            [ 'name' => [ 'ru' => 'Сент-Пьер и Микелон', 'en' =>  'Saint Pierre and Miquelon' ] ], 
            [ 'name' => [ 'ru' => 'Швеция', 'en' =>  'Sweden' ] ],
            [ 'name' => [ 'ru' => 'Американское Самоа', 'en' =>  'American Samoa' ] ], 
            [ 'name' => [ 'ru' => 'Антигуа и Барбуда', 'en' =>  'Antigua and Barbuda' ] ], 
            [ 'name' => [ 'ru' => 'Аргентина', 'en' =>  'Argentina' ] ],
            [ 'name' => [ 'ru' => 'Армения', 'en' =>  'Armenia' ] ],
            [ 'name' => [ 'ru' => 'Камбоджа', 'en' =>  'Cambodia' ] ],
            [ 'name' => [ 'ru' => 'Бонайре Синт Эстатиус и Саба', 'en' =>  'Bonaire Sint Eustatius and Saba' ] ], 
            [ 'name' => [ 'ru' => 'Португалия', 'en' =>  'Portugal' ] ],
            [ 'name' => [ 'ru' => 'Сент-Люсия', 'en' =>  'Saint Lucia' ] ], 
            [ 'name' => [ 'ru' => 'Босния и Герцеговина', 'en' =>  'Bosnia and Herzegovina' ] ], 
            [ 'name' => [ 'ru' => 'Лихтенштейн', 'en' =>  'Liechtenstein' ] ]
        ];

        foreach($countries as $country) {
            \App\Country::create($country);
        }
    }
}
